In [1]:
import numpy as np
import pandas as pd
import json

In [3]:
df=pd.read_csv('TOEFL_11/index.csv')
df.head()

,Unnamed: 0,Filename,Prompt,Language,Score Level,total word,distance,Hpoint,xmin,alpha,...,sigma,logtrue,file,pl_s,pl_C,pl_R2,log_d,log_m,log_k,log_R2
0,0,88.txt,P6,KOR,high,385,6.000000,8,2.0,2.273182,...,3.025490,0,88.txt,0.626725,27.346485,0.883300,3.478245,0.639538,1.090635,0.869275
1,1,278.txt,P6,DEU,medium,321,11.000000,7,3.0,2.421178,...,1.817156,0,278.txt,0.720874,31.641664,0.962596,3.573915,0.757765,1.032666,0.951214
2,2,348.txt,P1,TUR,high,363,8.306624,6,2.0,2.398038,...,1.739209,0,348.txt,0.621470,21.737883,0.965709,3.352892,0.874682,0.849857,0.889519
3,3,666.txt,P2,ZHO,medium,362,4.690416,6,5.0,3.410995,...,0.746383,0,666.txt,0.538645,18.320499,0.924139,2.824981,0.296708,1.441791,0.969115
4,4,733.txt,P6,TEL,medium,344,10.630146,7,6.0,3.124099,...,1.163868,0,733.txt,0.646729,25.998149,0.938335,3.393319,0.638436,1.093227,0.926643

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12098 entries, 0 to 12097
Data columns (total 21 columns):
Unnamed: 0     12098 non-null int64
Filename       12098 non-null object
Prompt         12098 non-null object
Language       12098 non-null object
Score Level    12098 non-null object
total word     12098 non-null int64
distance       12098 non-null float64
Hpoint         12098 non-null int64
xmin           12093 non-null float64
alpha          12093 non-null float64
mu             12093 non-null float64
sigma          12093 non-null float64
logtrue        12098 non-null int64
file           12098 non-null object
pl_s           12098 non-null float64
pl_C           12098 non-null float64
pl_R2          12098 non-null float64
log_d          12098 non-null float64
log_m          12098 non-null float64
log_k          12098 non-null float64
log_R2         12098 non-null float64
dtypes: float64(12), int64(4), object(5)
memory usage: 1.9+ MB

In [5]:
df.isna().sum()

Unnamed: 0     0
Filename       0
Prompt         0
Language       0
Score Level    0
total word     0
distance       0
Hpoint         0
xmin           5
alpha          5
mu             5
sigma          5
logtrue        0
file           0
pl_s           0
pl_C           0
pl_R2          0
log_d          0
log_m          0
log_k          0
log_R2         0
dtype: int64